/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.MetodosBD;
import Metodos.MetodoConection;
import Formularios.frmInscrip;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class frmCalendario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCalendario
     */
    public frmCalendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscarCalendario = new javax.swing.JTable();
        btnBuscarCalendario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbFiltro_Calendario = new javax.swing.JComboBox<>();
        btnInscripcionCalendario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblBuscarCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EXPERIENCIA_DE__FORMACION ", "FECHA ", "Lugar ", "Costo ", "Obs "
            }
        ));
        tblBuscarCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarCalendarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscarCalendario);
        if (tblBuscarCalendario.getColumnModel().getColumnCount() > 0) {
            tblBuscarCalendario.getColumnModel().getColumn(0).setHeaderValue("EXPERIENCIA_DE__FORMACION ");
            tblBuscarCalendario.getColumnModel().getColumn(1).setHeaderValue("FECHA ");
            tblBuscarCalendario.getColumnModel().getColumn(2).setHeaderValue("Lugar ");
            tblBuscarCalendario.getColumnModel().getColumn(3).setHeaderValue("Costo ");
            tblBuscarCalendario.getColumnModel().getColumn(4).setHeaderValue("Obs ");
        }

        btnBuscarCalendario.setText("Buscar");
        btnBuscarCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCalendarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por");

        cmbFiltro_Calendario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EXPERIENCIA_DE_FORMACION", "ROL_DEL_EDUCADOR_SCOUT", "ROL_DEL_EDUCADOR_SCOUT", "TALLERES", "CONOCIENDO_EL_MOVIMIENTO_SCOUT", "TALLERES", "LAS_OBLIGACIONES_INSTITUCIONALES", "LAS_OBLIGACIONES_INSTITUCIONALES", "EDUCACION_EN_LA_FE", "EL_EDUCADOR_Y_SU_FE", "SUPERVISION_(SUPERVISADO)", "PLANIFICANDO_EL_PROGRAMA_1", "PLANIFICANDO_EL_PROGRAMA_1", "LAS_OBLIGACIONES_INSTITUCIONALES", "LAS_OBLIGACIONES_INSTITUCIONALES", "LA_GESTION_INSTITUCIONAL", "EDUCACION_EN_LA_FE", "EL_EDUCADOR_Y_SU_FE", "ENCUENTRO_NACIONAL_DE_FORMADORES", "ENCUENTRO_NACIONAL_DE_FORMADORES", "ENCUENTRO_NACIONAL_DE_FORMADORES", "SUPERVISION_(SUPERVISADO)", "ANIMANDO_EL_PROGRAMA_1", "ANIMANDO_EL_PROGRAMA_1", "PLANIFICANDO_EL_PROGRAMA_1", "PLANIFICANDO_EL_PROGRAMA_1", "ANIMANDO_EL_PROGRAMA_1", "ANIMANDO_EL_PROGRAMA_1", "ROL_DEL_EDUCADOR_SCOUT", "ROL_DEL_EDUCADOR_SCOUT", "CONOCIENDO_EL_MOVIMIENTO_SCOUT", "TALLERES", " " }));
        cmbFiltro_Calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltro_CalendarioActionPerformed(evt);
            }
        });

        btnInscripcionCalendario.setText("Inscripcion a Experiencias");
        btnInscripcionCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionCalendarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(cmbFiltro_Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(btnBuscarCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInscripcionCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFiltro_Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCalendario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInscripcionCalendario))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBuscarCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarCalendarioMouseClicked


    }//GEN-LAST:event_tblBuscarCalendarioMouseClicked

    private void btnBuscarCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCalendarioActionPerformed
     MetodosBD metodosbd = new MetodosBD();
        //metodosbd.Buscar(txtValorbusqueda.getText(), cmbFiltro.getSelectedItem().toString(), tblBuscar);
        metodosbd.BuscarCalendario(cmbFiltro_Calendario.getSelectedItem().toString(), tblBuscarCalendario);

        

    }//GEN-LAST:event_btnBuscarCalendarioActionPerformed

    private void cmbFiltro_CalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltro_CalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFiltro_CalendarioActionPerformed

    private void btnInscripcionCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionCalendarioActionPerformed
        frmInscrip inscribime = new frmInscrip();
frmMaestra.jdpnEscritorio.add(inscribime);
inscribime.toFront();
       inscribime.show();    
         
    }//GEN-LAST:event_btnInscripcionCalendarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCalendario;
    private javax.swing.JButton btnInscripcionCalendario;
    private javax.swing.JComboBox<String> cmbFiltro_Calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuscarCalendario;
    // End of variables declaration//GEN-END:variables
}
