/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Metodos.MetodoConection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class frmMaestra extends javax.swing.JFrame {

    /**
     * Creates new form frmhome
     */
    public frmMaestra() {
       
       float escalar = 10F; // una ventana al 50% del tamaño de la pantalla
int ancho = (int)(Toolkit.getDefaultToolkit().getScreenSize(). width*escalar);
int alto = (int)(Toolkit.getDefaultToolkit().getScreenSize(). height*escalar);
this.setSize(ancho,alto);


 initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuFormacion = new javax.swing.JMenu();
        mnuFormacionMiFormacion = new javax.swing.JMenuItem();
        mnuFormacionCalendario = new javax.swing.JMenuItem();
        mnuFormacionInscripcion = new javax.swing.JMenuItem();
        mnuFormacionEsquemaFormacion = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyudaAcercaDe = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenuItem();
        mnuAyudaAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        javax.swing.GroupLayout jdpnEscritorioLayout = new javax.swing.GroupLayout(jdpnEscritorio);
        jdpnEscritorio.setLayout(jdpnEscritorioLayout);
        jdpnEscritorioLayout.setHorizontalGroup(
            jdpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jdpnEscritorioLayout.setVerticalGroup(
            jdpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuArchivoUsuario.setText("Usuarios");
        mnuArchivoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoUsuarioActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoUsuario);
        mnuArchivo.add(jSeparator1);
        mnuArchivo.add(jSeparator3);

        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoSalir);

        jMenuBar1.add(mnuArchivo);

        mnuFormacion.setText("Formacion");

        mnuFormacionMiFormacion.setText("Mi Formacion");
        mnuFormacionMiFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormacionMiFormacionActionPerformed(evt);
            }
        });
        mnuFormacion.add(mnuFormacionMiFormacion);

        mnuFormacionCalendario.setText("Calendario");
        mnuFormacionCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormacionCalendarioActionPerformed(evt);
            }
        });
        mnuFormacion.add(mnuFormacionCalendario);

        mnuFormacionInscripcion.setText("Inscripcion");
        mnuFormacionInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormacionInscripcionActionPerformed(evt);
            }
        });
        mnuFormacion.add(mnuFormacionInscripcion);

        mnuFormacionEsquemaFormacion.setText("Esquema de Formacion");
        mnuFormacionEsquemaFormacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormacionEsquemaFormacionActionPerformed(evt);
            }
        });
        mnuFormacion.add(mnuFormacionEsquemaFormacion);

        jMenuBar1.add(mnuFormacion);

        mnuAyuda.setText("Ayuda");

        mnuAyudaAcercaDe.setText("Acerca de ...");
        mnuAyudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAyudaAcercaDe);

        mnuAdministracion.setText("Contacto");
        mnuAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdministracionActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAdministracion);

        mnuAyudaAyuda.setText("Ayuda");
        mnuAyuda.add(mnuAyudaAyuda);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAyudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaAcercaDeActionPerformed
         frmAcercaDe acercaDe = new frmAcercaDe();
          jdpnEscritorio.add(acercaDe);
         acercaDe.show();
    }//GEN-LAST:event_mnuAyudaAcercaDeActionPerformed

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed
        //creamos el metodo de salida del boton SALIR
        System.exit(0);

    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    private void mnuArchivoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoUsuarioActionPerformed
        // TODO add your handling code here:
        frmUsuarios misUsuarios = new frmUsuarios(); // creo el objeto de la ventana frmUsuarios
        jdpnEscritorio.add(misUsuarios); // agrego al Desktop Pane (escritorio de ventana) el la ventana frmUsuarios
        misUsuarios.show(); // habilito la ventana frmUsuarios para que la peuda visualizar

    }//GEN-LAST:event_mnuArchivoUsuarioActionPerformed

    private void mnuFormacionCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormacionCalendarioActionPerformed
        frmCalendario jcalendar = new frmCalendario(); // creo el objeto de la ventana frmUsuarios
        jdpnEscritorio.add(jcalendar); // agrego al Desktop Pane (escritorio de ventana) el la ventana frmUsuarios
        jcalendar.show(); // habilito la ventana frmUsuarios para que la peuda visualizar
    }//GEN-LAST:event_mnuFormacionCalendarioActionPerformed

    private void mnuFormacionMiFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormacionMiFormacionActionPerformed
        frmMisCursos misCursos = new frmMisCursos();
        jdpnEscritorio.add(misCursos);
        misCursos.show();
    }//GEN-LAST:event_mnuFormacionMiFormacionActionPerformed

    private void mnuAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAdministracionActionPerformed

    private void mnuFormacionEsquemaFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormacionEsquemaFormacionActionPerformed
frmSistemaFormacion sistema = new frmSistemaFormacion();

    }//GEN-LAST:event_mnuFormacionEsquemaFormacionActionPerformed

    private void mnuFormacionInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormacionInscripcionActionPerformed
        frmInscrip inscribime = new frmInscrip();
        jdpnEscritorio.add(inscribime);
        inscribime.show();   // TODO add your handling code here:
    }//GEN-LAST:event_mnuFormacionInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMaestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public static javax.swing.JDesktopPane jdpnEscritorio;
    private javax.swing.JMenuItem mnuAdministracion;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoSalir;
    private javax.swing.JMenuItem mnuArchivoUsuario;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyudaAcercaDe;
    private javax.swing.JMenuItem mnuAyudaAyuda;
    private javax.swing.JMenu mnuFormacion;
    private javax.swing.JMenuItem mnuFormacionCalendario;
    private javax.swing.JMenuItem mnuFormacionEsquemaFormacion;
    private javax.swing.JMenuItem mnuFormacionInscripcion;
    private javax.swing.JMenuItem mnuFormacionMiFormacion;
    // End of variables declaration//GEN-END:variables
}
